pipeline:
  infrastructure:
    image: jmccann/drone-terraform:5
    actions:
      - validate
    sensitive: true
    root_dir: deploy
    environment:
      TF_VAR_aws_access_key_id: ${AWSACCESSKEY_SECRET}
      TF_VAR_aws_secret_key: ${AWSSECRETKEY_SECRET}
    vars:
      domain: shader.works
      domainAlias: shader_works
      subdomain: www.shader.works
      subdomainAlias: www_shader_works
      cdnSubDomain: cdn.shader.works
  build:
    image: ruby
    commands:
      - gem install jekyll bundler
      - bundle
      - jekyll build
