pipeline:
  infrastructure:
    image: jmccann/drone-terraform:5
    secrets:
      - source: aws_access_key_id
        target: tf_var_aws_access_key_id
      - source: aws_secret_access_key
        target: tf_var_aws_secret_key
    root_dir: provision/s3-hosting
    sensitive: true
    init_options:
      backend-config:
        - "bucket=terraform.state.storage"
        - "key=shader_works/terraform.tfstate"
        - "region=eu-west-1"
        - "encrypt=true"
        - "dynamodb_table=terraform-state-lock-dynamo"
    actions:
      - validate
      - plan
      # - apply
    var_files:
      - dev/dev.infrastructure.tfvars
  build:
    image: ruby
    commands:
      - gem install jekyll bundler
      - bundle
      - bundle exec jekyll build
  upload:
    image: plugins/s3
    bucket: www.shader.works
    region: eu-west-1
    secrets: [aws_access_key_id, aws_secret_access_key]
    source: _site/**/*
    target: /
    strip_prefix: _site/
    when:
      branch: master