pipeline:
  infrastructure:
    image: jmccann/drone-terraform:5
    secrets:
      - source: AWSACCESSKEY_SECRET
        target: tf_var_aws_access_key_id
      - source: AWSSECRETKEY_SECRET
        target: tf_var_aws_secret_key
    actions:
      - validate
    sensitive: true
    root_dir: deploy
    vars:
      domain: shader.works
      domainAlias: shader_works
      subdomain: www.shader.works
      subdomainAlias: www_shader_works
      cdnSubDomain: cdn.shader.works
  build:
    image: ruby
    commands:
      - gem install jekyll bundler
      - bundle
      - jekyll build
