pipeline:
  infrastructure:
    image: jmccann/drone-terraform:1
    plan: false
    root_dir: deploy
    vars:
      domain: shader.works
      domainAlias: shader_works
      subdomain: www.shader.works
      subdomainAlias: www_shader_works
      cdnSubDomain: cdn.shader.works
      aws_access_key_id: 
        from_secret: AWSACCESSKEY_SECRET
      aws_secret_key: 
        from_secret: AWSSECRETKEY_SECRET
  build:
    image: ruby
    commands:
      - gem install jekyll bundler
      - bundle
      - jekyll build
