pipeline:
  infrastructure:
    image: jmccann/drone-terraform:5
    secrets:
      - source: aws_access_key_id
        target: tf_var_aws_access_key_id
      - source: aws_secret_access_key
        target: tf_var_aws_secret_key
    root_dir: provision/s3-hosting
    sensitive: true
    remote:
      backend: S3
      config:
        bucket: terraform.state.storage
        region: eu-west-1
        key: shader_works/terraform.tfstate
        encrypt: true
        dynamodb_table: terraform-state-lock-dynamo
    actions:
      - validate
      - plan
      # - apply
    vars:
      region: eu-west-1
      domain: shader.works
      domainAlias: shader_works
      subdomain: www.shader.works
      subdomainAlias: www_shader_works
      cdnSubDomain: cdn.shader.works
  build:
    image: ruby
    commands:
      - gem install jekyll bundler
      - bundle
      - bundle exec jekyll build
  upload:
    image: plugins/s3
    bucket: www.shader.works
    region: eu-west-1
    secrets: [aws_access_key_id, aws_secret_access_key]
    source: _site/**/*
    target: /
    strip_prefix: _site/
    when:
      branch: master